# Setup
title:        EARTH STATION
tagline:      the earth station of meteorological satellite Random
baseurl:      ""
paginate:     5
timezone: Asia/Shanghai

# About/contact
author:
  name:       msx.pan
  url:        https://github.com/msxpan 

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown

